-- sprint85_drugs_1000.sql
-- Phlox — Expansão GRANDE da base de medicamentos (adiciona ao que já existe).
-- Cobertura alargada de fármacos vendidos em Portugal, por classe terapêutica,
-- com DCI, classe, para que serve, receita (regras INFARMED), efeitos e cuidados.
--
-- Apenas DCIs/genéricos + marcas comuns. `source='manual'`, confidence=1.0.
-- ON CONFLICT DO NOTHING garante idempotência (não duplica brand+DCI).
-- 2026-06-07.

-- 1) Limpar duplicados PRÉ-EXISTENTES (sprints anteriores criaram repetidos,
--    ex: humalog/insulina lispro). Mantém a linha mais antiga (menor ctid),
--    preferindo as 'manual' sobre 'ai_cache'. Necessário antes do índice único.
delete from infarmed_drugs a
using infarmed_drugs b
where lower(coalesce(a.brand_name,'')) = lower(coalesce(b.brand_name,''))
  and lower(a.active_ingredient) = lower(b.active_ingredient)
  and (
    -- b é "melhor" → apaga a
    (b.source = 'manual' and a.source <> 'manual')
    or (b.source = a.source and a.ctid > b.ctid)
  );

-- 1b) Limpa cache IA POBRE (entradas antigas incompletas que poluíam resultados,
--     ex: guronsan só com "precisa de receita"). Assim os inserts 'manual' ganham.
delete from infarmed_drugs
where source = 'ai_cache'
  and (what_it_is is null or length(coalesce(what_it_is,'')) < 20 or coalesce(array_length(what_it_treats,1),0) = 0);

-- 2) Constraint de unicidade (brand+DCI em minúsculas) para idempotência real.
create unique index if not exists infarmed_uniq_brand_active
  on infarmed_drugs (lower(coalesce(brand_name,'')), lower(active_ingredient));

insert into infarmed_drugs (brand_name, active_ingredient, registry_codes, forms, strengths, therapeutic_class, what_it_is, what_it_treats, symptoms, how_to_take, prescription, prescription_note, common_side_effects, cautions, avoid_if, good_to_know, source, confidence) values

-- ═══ ANALGÉSICOS / AINEs / OPIÓIDES ═══
('Nimed','Nimesulida',NULL,ARRAY['comprimido','saqueta'],ARRAY['100mg'],'AINE','anti-inflamatório para dor e inflamação aguda',ARRAY['dor aguda','dismenorreia','dor músculo-esquelética'],ARRAY['dor','inflamação'],'100mg 2x/dia após refeições, máximo 15 dias.','com receita médica','MSRM. Risco hepático — uso curto.',ARRAY['dor de estômago','elevação enzimas hepáticas'],ARRAY['curta duração','vigiar fígado'],ARRAY['doença hepática','úlcera activa'],NULL,'manual',1.0),
('Feldene','Piroxicam',NULL,ARRAY['cápsula','gel'],ARRAY['10mg','20mg'],'AINE','anti-inflamatório de longa duração',ARRAY['artrite','dor músculo-esquelética'],ARRAY['dor','inflamação'],'20mg/dia.','com receita médica','MSRM.',ARRAY['GI','retenção líquidos'],ARRAY['risco GI elevado em idosos'],ARRAY['úlcera activa'],NULL,'manual',1.0),
('Celebrex','Celecoxib',NULL,ARRAY['cápsula'],ARRAY['100mg','200mg'],'AINE inibidor COX-2','anti-inflamatório com menos risco gástrico',ARRAY['artrose','artrite reumatóide','dor'],ARRAY['dor','inflamação'],'100-200mg 1-2x/dia.','com receita médica','MSRM.',ARRAY['risco cardiovascular','edema','HTA'],ARRAY['cuidado em doença CV'],ARRAY['doença CV grave','3º trimestre gravidez'],NULL,'manual',1.0),
('Arcoxia','Etoricoxib',NULL,ARRAY['comprimido'],ARRAY['30mg','60mg','90mg','120mg'],'AINE inibidor COX-2','anti-inflamatório COX-2',ARRAY['artrose','gota aguda','dor'],ARRAY['dor','inflamação'],'30-120mg/dia conforme indicação.','com receita médica','MSRM.',ARRAY['HTA','edema','risco CV'],ARRAY['vigiar TA'],ARRAY['HTA não controlada','doença CV'],NULL,'manual',1.0),
('Ben-u-ron + Codeína','Paracetamol + Codeína',NULL,ARRAY['comprimido'],ARRAY['500+30mg'],'analgésico opióide fraco + paracetamol','associação para dor moderada',ARRAY['dor moderada que não cede a paracetamol'],ARRAY['dor moderada'],'1-2 comprimidos 6/6h.','com receita médica','MSRM.',ARRAY['obstipação','sonolência','náuseas'],ARRAY['não conduzir','não exceder paracetamol 4g/dia'],ARRAY['depressão respiratória','crianças'],NULL,'manual',1.0),
('Morfina','Sulfato de morfina',NULL,ARRAY['comprimido LP','solução oral','injectável'],ARRAY['10mg','30mg','60mg'],'opióide forte','analgésico opióide forte para dor intensa',ARRAY['dor oncológica','dor aguda grave','dor crónica grave'],ARRAY['dor grave'],'Dose titulada individualmente.','com receita médica especial','MSRM-especial (receita amarela).',ARRAY['obstipação','sonolência','náuseas','depressão respiratória','dependência'],ARRAY['titulação cuidadosa','laxante profilático'],ARRAY['depressão respiratória','íleo paralítico'],NULL,'manual',1.0),
('Palexia','Tapentadol',NULL,ARRAY['comprimido LP'],ARRAY['50mg','100mg','150mg','200mg','250mg'],'opióide forte','analgésico opióide para dor crónica grave e neuropática',ARRAY['dor crónica grave','dor neuropática'],ARRAY['dor grave'],'50mg 12/12h, titular.','com receita médica especial','MSRM-especial.',ARRAY['náuseas','tonturas','obstipação','sonolência'],ARRAY['não conduzir','retirada gradual'],ARRAY['depressão respiratória','epilepsia não controlada'],NULL,'manual',1.0),
('Codeína','Codeína',NULL,ARRAY['comprimido','xarope'],ARRAY['30mg'],'opióide fraco / antitússico','opióide fraco para dor e tosse',ARRAY['dor moderada','tosse seca'],ARRAY['dor','tosse'],'30mg 4-6/6h.','com receita médica','MSRM.',ARRAY['obstipação','sonolência'],ARRAY['metabolizadores rápidos CYP2D6 — risco','não em <12a'],ARRAY['crianças <12a','amamentação'],NULL,'manual',1.0),
('Buscopan composto','Butilescopolamina + Paracetamol',NULL,ARRAY['comprimido'],ARRAY['10+500mg'],'antiespasmódico + analgésico','para cólicas com dor',ARRAY['cólicas','dismenorreia'],ARRAY['cólica','dor'],'1-2 comprimidos 3x/dia.','sem receita','MNSRM.',ARRAY['boca seca','obstipação'],ARRAY[]::text[],ARRAY['glaucoma fechado','obstrução urinária'],NULL,'manual',1.0),
('Toradol','Cetorolaco',NULL,ARRAY['comprimido','injectável'],ARRAY['10mg','30mg'],'AINE potente','AINE forte para dor aguda de curta duração',ARRAY['dor pós-operatória','cólica renal'],ARRAY['dor intensa'],'10mg 6/6h, máx 5 dias.','com receita médica','MSRM. Máx 5 dias.',ARRAY['hemorragia GI','IR'],ARRAY['curta duração apenas'],ARRAY['úlcera','IR','hemorragia'],NULL,'manual',1.0),

-- ═══ ANTIBIÓTICOS ═══
('Amoxicilina','Amoxicilina',NULL,ARRAY['cápsula','suspensão'],ARRAY['250mg','500mg','1000mg'],'antibiótico penicilina','antibiótico de largo espectro',ARRAY['amigdalite','otite','sinusite','pneumonia','ITU'],ARRAY['infecção'],'500-1000mg 8/8h.','com receita médica','MSRM.',ARRAY['diarreia','exantema','candidíase'],ARRAY['completar tratamento'],ARRAY['alergia a penicilinas'],NULL,'manual',1.0),
('Penicilina V','Fenoximetilpenicilina',NULL,ARRAY['comprimido','suspensão'],ARRAY['250mg','500mg'],'antibiótico penicilina','penicilina oral para infecções estreptocócicas',ARRAY['faringoamigdalite estreptocócica','profilaxia febre reumática'],ARRAY['infecção garganta'],'500mg 8/8h.','com receita médica','MSRM.',ARRAY['GI','exantema'],ARRAY[]::text[],ARRAY['alergia penicilinas'],NULL,'manual',1.0),
('Flucloxacilina','Flucloxacilina',NULL,ARRAY['cápsula'],ARRAY['500mg'],'antibiótico penicilina anti-estafilocócica','antibiótico para infecções de pele por Staphylococcus',ARRAY['celulite','impetigo','infecções de pele'],ARRAY['infecção pele'],'500mg 6/6h em jejum.','com receita médica','MSRM.',ARRAY['GI','hepatotoxicidade rara'],ARRAY['tomar em jejum'],ARRAY['alergia penicilinas'],NULL,'manual',1.0),
('Cefradina','Cefradina',NULL,ARRAY['cápsula','suspensão'],ARRAY['500mg'],'cefalosporina 1ª geração','cefalosporina para infecções comuns',ARRAY['infecções pele','ITU','respiratórias'],ARRAY['infecção'],'500mg 6/6h.','com receita médica','MSRM.',ARRAY['GI'],ARRAY['alergia cruzada penicilinas'],ARRAY['alergia grave'],NULL,'manual',1.0),
('Levofloxacina','Levofloxacina',NULL,ARRAY['comprimido','injectável'],ARRAY['250mg','500mg'],'antibiótico fluoroquinolona','quinolona respiratória',ARRAY['pneumonia','sinusite','ITU complicada','prostatite'],ARRAY['infecção respiratória'],'500mg/dia.','com receita médica','MSRM. Reservar — risco tendinopatia.',ARRAY['tendinopatia','prolongamento QT','náuseas','fotossensibilidade'],ARRAY['evitar sol','risco rotura tendão'],ARRAY['gravidez','epilepsia','crianças'],NULL,'manual',1.0),
('Moxifloxacina','Moxifloxacina',NULL,ARRAY['comprimido'],ARRAY['400mg'],'antibiótico fluoroquinolona','quinolona respiratória',ARRAY['pneumonia','sinusite','exacerbação DPOC'],ARRAY['infecção respiratória'],'400mg/dia.','com receita médica','MSRM.',ARRAY['prolongamento QT','tendinopatia','hepatotoxicidade'],ARRAY['vigiar QT'],ARRAY['QT longo','gravidez'],NULL,'manual',1.0),
('Norfloxacina','Norfloxacina',NULL,ARRAY['comprimido'],ARRAY['400mg'],'antibiótico fluoroquinolona','quinolona para ITU',ARRAY['ITU','prostatite'],ARRAY['infecção urinária'],'400mg 12/12h.','com receita médica','MSRM.',ARRAY['náuseas','tendinopatia'],ARRAY['hidratação'],ARRAY['gravidez','crianças'],NULL,'manual',1.0),
('Fosfomicina','Fosfomicina trometamol',NULL,ARRAY['saqueta'],ARRAY['3g'],'antibiótico','antibiótico de dose única para ITU não complicada',ARRAY['cistite não complicada'],ARRAY['ardor urinar'],'1 saqueta dose única ao deitar, bexiga vazia.','com receita médica','MSRM.',ARRAY['diarreia','náuseas'],ARRAY['tomar com estômago vazio'],ARRAY['IR grave'],'Toma única é muito conveniente.','manual',1.0),
('Nitrofurantoína','Nitrofurantoína',NULL,ARRAY['cápsula'],ARRAY['100mg'],'antibiótico urinário','antibiótico específico para ITU baixa',ARRAY['cistite','profilaxia ITU recorrente'],ARRAY['infecção urinária'],'100mg 12/12h, 5 dias.','com receita médica','MSRM.',ARRAY['náuseas','coloração urina','fibrose pulmonar (uso longo)'],ARRAY['com alimentos'],ARRAY['IR (TFG<45)','fim de gravidez','défice G6PD'],NULL,'manual',1.0),
('Tavanic','Levofloxacina',NULL,ARRAY['comprimido'],ARRAY['500mg'],'antibiótico fluoroquinolona','quinolona respiratória (marca)',ARRAY['pneumonia','ITU complicada'],ARRAY['infecção'],'500mg/dia.','com receita médica','MSRM.',ARRAY['tendinopatia','QT'],ARRAY['evitar sol'],ARRAY['gravidez'],NULL,'manual',1.0),
('Zinnat','Cefuroxima',NULL,ARRAY['comprimido','suspensão'],ARRAY['250mg','500mg'],'cefalosporina 2ª geração','cefalosporina (marca)',ARRAY['otite','sinusite','pneumonia'],ARRAY['infecção'],'250-500mg 12/12h.','com receita médica','MSRM.',ARRAY['GI'],ARRAY['alergia cruzada penicilinas'],ARRAY['alergia grave'],NULL,'manual',1.0),

-- ═══ CARDIOVASCULAR ═══
('Triatec','Ramipril',NULL,ARRAY['comprimido'],ARRAY['2.5mg','5mg','10mg'],'IECA','medicamento para HTA e protecção cardíaca (marca)',ARRAY['HTA','IC','pós-EAM'],ARRAY['HTA'],'2.5-10mg/dia.','com receita médica','MSRM.',ARRAY['tosse seca','tonturas'],ARRAY['vigiar K+ e creatinina'],ARRAY['gravidez','angioedema prévio'],NULL,'manual',1.0),
('Perindopril','Perindopril',NULL,ARRAY['comprimido'],ARRAY['2.5mg','5mg','10mg'],'IECA','IECA para HTA e doença coronária',ARRAY['HTA','doença coronária estável','IC'],ARRAY['HTA'],'5-10mg/dia de manhã.','com receita médica','MSRM.',ARRAY['tosse seca','tonturas'],ARRAY['vigiar K+'],ARRAY['gravidez'],NULL,'manual',1.0),
('Coversyl','Perindopril',NULL,ARRAY['comprimido'],ARRAY['5mg','10mg'],'IECA','IECA (marca)',ARRAY['HTA','doença coronária'],ARRAY['HTA'],'5-10mg/dia.','com receita médica','MSRM.',ARRAY['tosse seca'],ARRAY['vigiar K+'],ARRAY['gravidez'],NULL,'manual',1.0),
('Candesartan','Candesartan',NULL,ARRAY['comprimido'],ARRAY['8mg','16mg','32mg'],'ARA-II','para HTA e IC, sem tosse',ARRAY['HTA','IC'],ARRAY['HTA'],'8-32mg/dia.','com receita médica','MSRM.',ARRAY['tonturas','hipercaliemia'],ARRAY['vigiar K+ e creatinina'],ARRAY['gravidez'],NULL,'manual',1.0),
('Telmisartan','Telmisartan',NULL,ARRAY['comprimido'],ARRAY['40mg','80mg'],'ARA-II','para HTA, longa duração',ARRAY['HTA','protecção CV'],ARRAY['HTA'],'40-80mg/dia.','com receita médica','MSRM.',ARRAY['tonturas'],ARRAY['vigiar K+'],ARRAY['gravidez'],NULL,'manual',1.0),
('Irbesartan','Irbesartan',NULL,ARRAY['comprimido'],ARRAY['150mg','300mg'],'ARA-II','para HTA e protecção renal em DM2',ARRAY['HTA','nefropatia diabética'],ARRAY['HTA'],'150-300mg/dia.','com receita médica','MSRM.',ARRAY['tonturas'],ARRAY['vigiar K+'],ARRAY['gravidez'],NULL,'manual',1.0),
('Lercanidipina','Lercanidipina',NULL,ARRAY['comprimido'],ARRAY['10mg','20mg'],'bloqueador canais cálcio','para HTA, menos edema que amlodipina',ARRAY['HTA'],ARRAY['HTA'],'10-20mg/dia antes refeição.','com receita médica','MSRM.',ARRAY['edema maleolar','rubor'],ARRAY[]::text[],ARRAY['choque','EAM recente'],NULL,'manual',1.0),
('Diltiazem','Diltiazem',NULL,ARRAY['comprimido LP'],ARRAY['90mg','120mg','180mg','240mg'],'bloqueador cálcio não-dihidropiridínico','para HTA, angina e controlo de frequência',ARRAY['HTA','angina','controlo FC em FA'],ARRAY['HTA','arritmia'],'120-240mg/dia LP.','com receita médica','MSRM.',ARRAY['bradicárdia','edema','obstipação'],ARRAY['evitar com beta-bloqueante'],ARRAY['IC sistólica','BAV'],NULL,'manual',1.0),
('Nebivolol','Nebivolol',NULL,ARRAY['comprimido'],ARRAY['5mg'],'beta-bloqueante','beta-bloqueante vasodilatador para HTA e IC',ARRAY['HTA','IC'],ARRAY['HTA'],'5mg/dia.','com receita médica','MSRM.',ARRAY['fadiga','bradicárdia'],ARRAY['não parar abrupto'],ARRAY['asma grave','bradicárdia'],NULL,'manual',1.0),
('Nebilet','Nebivolol',NULL,ARRAY['comprimido'],ARRAY['5mg'],'beta-bloqueante','beta-bloqueante (marca)',ARRAY['HTA','IC'],ARRAY['HTA'],'5mg/dia.','com receita médica','MSRM.',ARRAY['fadiga','bradicárdia'],ARRAY['não parar abrupto'],ARRAY['asma','bradicárdia'],NULL,'manual',1.0),
('Sotalol','Sotalol',NULL,ARRAY['comprimido'],ARRAY['80mg','160mg'],'antiarrítmico / beta-bloqueante','para arritmias',ARRAY['FA','arritmias ventriculares'],ARRAY['arritmia'],'80-160mg 12/12h.','com receita médica','MSRM. Prolonga QT.',ARRAY['prolongamento QT','bradicárdia'],ARRAY['vigiar QT e K+'],ARRAY['QT longo','asma'],NULL,'manual',1.0),
('Pravastatina','Pravastatina',NULL,ARRAY['comprimido'],ARRAY['20mg','40mg'],'estatina','baixa o colesterol, poucas interacções',ARRAY['dislipidemia'],ARRAY['colesterol'],'20-40mg ao deitar.','com receita médica','MSRM.',ARRAY['mialgias'],ARRAY['menos interacções que outras'],ARRAY['hepatopatia activa'],NULL,'manual',1.0),
('Ezetimiba','Ezetimiba',NULL,ARRAY['comprimido'],ARRAY['10mg'],'inibidor da absorção de colesterol','baixa colesterol, combina com estatina',ARRAY['dislipidemia'],ARRAY['colesterol'],'10mg/dia.','com receita médica','MSRM.',ARRAY['GI','mialgias'],ARRAY['frequente em associação à estatina'],ARRAY['hepatopatia activa com estatina'],NULL,'manual',1.0),
('Fenofibrato','Fenofibrato',NULL,ARRAY['cápsula'],ARRAY['145mg','200mg'],'fibrato','baixa os triglicéridos',ARRAY['hipertrigliceridemia','dislipidemia mista'],ARRAY['triglicéridos altos'],'145mg/dia com refeição.','com receita médica','MSRM.',ARRAY['mialgias','GI','litíase biliar'],ARRAY['risco miopatia com estatina'],ARRAY['doença hepática/biliar grave'],NULL,'manual',1.0),
('Trombyl','Ácido acetilsalicílico',NULL,ARRAY['comprimido'],ARRAY['75mg','150mg'],'antiagregante','AAS baixa dose para prevenção CV',ARRAY['prevenção EAM/AVC'],ARRAY['história CV'],'75-150mg/dia.','sem receita','MNSRM.',ARRAY['hemorragia digestiva'],ARRAY['suspender antes de cirurgia'],ARRAY['úlcera activa'],NULL,'manual',1.0),
('Clexane','Enoxaparina',NULL,ARRAY['seringa SC'],ARRAY['20mg','40mg','60mg','80mg'],'heparina de baixo peso molecular','anticoagulante injectável',ARRAY['profilaxia/tratamento TVP/TEP','SCA'],ARRAY['anticoagulação'],'Dose conforme peso e indicação, SC.','com receita médica','MSRM.',ARRAY['hemorragia','hematoma local','trombocitopenia'],ARRAY['ajuste por peso e função renal'],ARRAY['hemorragia activa','trombocitopenia por heparina'],NULL,'manual',1.0),
('Sintrom','Acenocumarol',NULL,ARRAY['comprimido'],ARRAY['1mg','4mg'],'anticoagulante antagonista vit K','anticoagulante oral (controlo por INR)',ARRAY['FA','TVP/TEP','válvula mecânica'],ARRAY['anticoagulação'],'Dose ajustada ao INR.','com receita médica','MSRM. INR regular.',ARRAY['hemorragia'],ARRAY['muitas interacções','dieta estável (vit K)'],ARRAY['gravidez','hemorragia activa'],NULL,'manual',1.0),

-- ═══ DIABETES / ENDÓCRINO ═══
('Metformina','Metformina',NULL,ARRAY['comprimido'],ARRAY['500mg','850mg','1000mg'],'antidiabético biguanida','1ª linha da diabetes tipo 2',ARRAY['DM2','pré-diabetes','SOP'],ARRAY['diabetes'],'500-1000mg 2x/dia com refeições.','com receita médica','MSRM.',ARRAY['diarreia','náuseas','défice B12','sabor metálico'],ARRAY['suspender em contraste iodado','com refeições'],ARRAY['IR grave (TFG<30)','acidose'],NULL,'manual',1.0),
('Gliclazida','Gliclazida',NULL,ARRAY['comprimido LM'],ARRAY['30mg','60mg'],'sulfonilureia','antidiabético que estimula a insulina',ARRAY['DM2'],ARRAY['diabetes'],'30-120mg/dia ao pequeno-almoço.','com receita médica','MSRM.',ARRAY['hipoglicémia','aumento peso'],ARRAY['risco hipoglicémia em idosos'],ARRAY['DM1','IR/IH grave'],NULL,'manual',1.0),
('Glimepirida','Glimepirida',NULL,ARRAY['comprimido'],ARRAY['1mg','2mg','4mg'],'sulfonilureia','antidiabético oral',ARRAY['DM2'],ARRAY['diabetes'],'1-4mg/dia.','com receita médica','MSRM.',ARRAY['hipoglicémia','aumento peso'],ARRAY['vigiar hipoglicémia'],ARRAY['DM1'],NULL,'manual',1.0),
('Sitagliptina','Sitagliptina',NULL,ARRAY['comprimido'],ARRAY['100mg'],'inibidor DPP-4','antidiabético oral, baixo risco hipoglicémia',ARRAY['DM2'],ARRAY['diabetes'],'100mg/dia.','com receita médica','MSRM.',ARRAY['cefaleia','pancreatite rara'],ARRAY['ajuste IR'],ARRAY['pancreatite'],NULL,'manual',1.0),
('Empagliflozina','Empagliflozina',NULL,ARRAY['comprimido'],ARRAY['10mg','25mg'],'inibidor SGLT2','antidiabético que protege coração e rim',ARRAY['DM2','IC','DRC'],ARRAY['diabetes','IC'],'10-25mg/dia.','com receita médica','MSRM.',ARRAY['infecções genitais','poliúria','cetoacidose euglicémica'],ARRAY['higiene','hidratação'],ARRAY['DM1'],NULL,'manual',1.0),
('Dapagliflozina','Dapagliflozina',NULL,ARRAY['comprimido'],ARRAY['5mg','10mg'],'inibidor SGLT2','protege coração e rim',ARRAY['DM2','IC','DRC'],ARRAY['diabetes','IC'],'10mg/dia.','com receita médica','MSRM.',ARRAY['infecções genitais'],ARRAY['hidratação'],ARRAY['DM1'],NULL,'manual',1.0),
('Liraglutido','Liraglutido',NULL,ARRAY['caneta SC'],ARRAY['0.6mg','1.2mg','1.8mg'],'agonista GLP-1','injecção diária para DM2 e peso',ARRAY['DM2','obesidade'],ARRAY['diabetes','obesidade'],'Titular 0.6→1.8mg/dia SC.','com receita médica','MSRM.',ARRAY['náuseas','vómitos'],ARRAY['titulação lenta'],ARRAY['MTC','MEN2'],NULL,'manual',1.0),
('Insulatard','Insulina NPH',NULL,ARRAY['caneta','frasco'],ARRAY['100U/mL'],'insulina intermédia','insulina basal de duração intermédia',ARRAY['DM1','DM2'],ARRAY['diabetes'],'1-2x/dia SC.','com receita médica','MSRM.',ARRAY['hipoglicémia','aumento peso'],ARRAY['rotação locais'],ARRAY['hipoglicémia activa'],NULL,'manual',1.0),
('Toujeo','Insulina glargina U300',NULL,ARRAY['caneta'],ARRAY['300U/mL'],'insulina basal','insulina basal concentrada de 24h+',ARRAY['DM1','DM2'],ARRAY['diabetes'],'1x/dia SC à mesma hora.','com receita médica','MSRM.',ARRAY['hipoglicémia'],ARRAY['rotação locais'],ARRAY['hipoglicémia activa'],NULL,'manual',1.0),
('Tirosint','Levotiroxina',NULL,ARRAY['cápsula mole','comprimido'],ARRAY['25mcg','50mcg','75mcg','100mcg'],'hormona tiroideia','substituto da hormona tiroideia',ARRAY['hipotiroidismo'],ARRAY['hipotiroidismo'],'Em jejum, 30-60min antes do pequeno-almoço.','com receita médica','MSRM.',ARRAY['palpitações se dose alta'],ARRAY['afastar de cálcio/ferro/café'],ARRAY['hipertiroidismo'],NULL,'manual',1.0),
('Tiamazol','Tiamazol',NULL,ARRAY['comprimido'],ARRAY['5mg','20mg'],'antitiroideu','reduz a produção de hormona tiroideia',ARRAY['hipertiroidismo','doença de Graves'],ARRAY['hipertiroidismo'],'Dose individual, titulada.','com receita médica','MSRM.',ARRAY['exantema','agranulocitose (raro grave)','hepatotoxicidade'],ARRAY['vigiar hemograma — febre/dor garganta = parar e analisar'],ARRAY['agranulocitose prévia'],NULL,'manual',1.0),

-- ═══ RESPIRATÓRIO ═══
('Foster','Beclometasona + Formoterol',NULL,ARRAY['inalador'],ARRAY['100/6','200/6'],'corticoide inalado + LABA','inalador de manutenção para asma/DPOC',ARRAY['asma','DPOC'],ARRAY['asma','DPOC'],'1-2 inalações 2x/dia.','com receita médica','MSRM. Bochechar após.',ARRAY['candidíase oral','rouquidão'],ARRAY['bochechar'],ARRAY['monoterapia asma'],NULL,'manual',1.0),
('Spiriva','Tiotrópio',NULL,ARRAY['inalador'],ARRAY['18mcg','2.5mcg'],'broncodilatador anticolinérgico longa acção','inalador de manutenção da DPOC',ARRAY['DPOC','asma (adjuvante)'],ARRAY['DPOC'],'1 inalação/dia.','com receita médica','MSRM.',ARRAY['boca seca','retenção urinária'],ARRAY[]::text[],ARRAY['glaucoma fechado','hipertrofia prostática grave'],NULL,'manual',1.0),
('Atrovent','Brometo de ipratrópio',NULL,ARRAY['inalador','nebulização'],ARRAY['20mcg','250mcg/mL'],'broncodilatador anticolinérgico curta acção','broncodilatador para DPOC/crise',ARRAY['DPOC','broncospasmo'],ARRAY['dispneia'],'2 inalações 3-4x/dia.','com receita médica','MSRM.',ARRAY['boca seca'],ARRAY[]::text[],ARRAY['glaucoma fechado'],NULL,'manual',1.0),
('Singulair','Montelucaste',NULL,ARRAY['comprimido','granulado'],ARRAY['4mg','5mg','10mg'],'antagonista dos leucotrienos','para asma e rinite alérgica',ARRAY['asma','rinite alérgica'],ARRAY['asma','alergia'],'10mg/dia ao deitar.','com receita médica','MSRM.',ARRAY['cefaleia','alterações humor/sono'],ARRAY['vigiar alterações comportamentais'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Pulmicort','Budesonida',NULL,ARRAY['inalador','nebulização'],ARRAY['200mcg','0.5mg/mL'],'corticoide inalado','corticoide inalado para asma',ARRAY['asma'],ARRAY['asma'],'1-2 inalações 2x/dia.','com receita médica','MSRM. Bochechar.',ARRAY['candidíase','rouquidão'],ARRAY['bochechar'],ARRAY[]::text[],NULL,'manual',1.0),
('Bricanyl','Terbutalina',NULL,ARRAY['inalador','injectável'],ARRAY['0.5mg/dose'],'broncodilatador beta-2 curta acção','broncodilatador de alívio',ARRAY['asma','broncospasmo'],ARRAY['dispneia'],'1-2 inalações SOS.','com receita médica','MSRM.',ARRAY['tremor','taquicárdia'],ARRAY['SOS'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),

-- ═══ GASTRO ═══
('Esomeprazol','Esomeprazol',NULL,ARRAY['comprimido','cápsula'],ARRAY['20mg','40mg'],'inibidor da bomba de protões','reduz o ácido do estômago',ARRAY['refluxo','úlcera','H. pylori'],ARRAY['azia','refluxo'],'20-40mg/dia antes pequeno-almoço.','com receita médica','MSRM.',ARRAY['cefaleia','diarreia'],ARRAY['uso prolongado: B12/Mg'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Controloc','Pantoprazol',NULL,ARRAY['comprimido'],ARRAY['20mg','40mg'],'inibidor bomba protões','IBP (marca)',ARRAY['refluxo','úlcera'],ARRAY['azia'],'20-40mg/dia.','depende da dose','20mg ≤14 cp MNSRM, resto MSRM.',ARRAY['cefaleia','diarreia'],ARRAY['uso prolongado'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Domperidona','Domperidona',NULL,ARRAY['comprimido','suspensão'],ARRAY['10mg'],'antiemético procinético','contra náuseas e refluxo',ARRAY['náuseas','vómitos','gastroparesia'],ARRAY['náuseas'],'10mg 3x/dia antes refeições, máx 7 dias.','com receita médica','MSRM. Risco QT.',ARRAY['prolongamento QT'],ARRAY['dose mínima, tempo curto'],ARRAY['QT longo','hepatopatia'],NULL,'manual',1.0),
('Ondansetron','Ondansetron',NULL,ARRAY['comprimido','injectável'],ARRAY['4mg','8mg'],'antiemético antagonista 5-HT3','antiemético potente',ARRAY['náuseas/vómitos pós-op','quimioterapia'],ARRAY['náuseas','vómitos'],'4-8mg conforme indicação.','com receita médica','MSRM.',ARRAY['obstipação','cefaleia','prolongamento QT'],ARRAY['vigiar QT'],ARRAY['QT longo','sd. QT congénito'],NULL,'manual',1.0),
('Espasmo Canulase','Enzimas digestivas',NULL,ARRAY['comprimido'],NULL,'enzimas digestivas','auxiliar da digestão',ARRAY['má digestão','flatulência'],ARRAY['má digestão'],'Às refeições.','sem receita','MNSRM.',ARRAY['raros'],ARRAY[]::text[],ARRAY['pancreatite aguda'],NULL,'manual',1.0),
('Kreon','Pancreatina',NULL,ARRAY['cápsula'],ARRAY['10000U','25000U','40000U'],'enzimas pancreáticas','substitui enzimas do pâncreas',ARRAY['insuficiência pancreática','fibrose quística','pancreatite crónica'],ARRAY['má absorção'],'Às refeições, dose conforme refeição.','com receita médica','MSRM.',ARRAY['GI'],ARRAY['tomar com as refeições'],ARRAY['hipersensibilidade a porco'],NULL,'manual',1.0),
('Mesalazina','Mesalazina',NULL,ARRAY['comprimido LP','supositório','enema'],ARRAY['500mg','1g','1.5g'],'aminosalicilato','anti-inflamatório intestinal para DII',ARRAY['colite ulcerosa','doença de Crohn'],ARRAY['DII'],'Dose individual.','com receita médica','MSRM.',ARRAY['cefaleia','GI','nefrotoxicidade rara'],ARRAY['vigiar função renal'],ARRAY['hipersensibilidade salicilatos'],NULL,'manual',1.0),

-- ═══ NEURO / PSIQUIATRIA ═══
('Escitalopram','Escitalopram',NULL,ARRAY['comprimido','gotas'],ARRAY['10mg','20mg'],'ISRS antidepressivo','antidepressivo para depressão e ansiedade',ARRAY['depressão','ansiedade','pânico'],ARRAY['depressão','ansiedade'],'10-20mg/dia.','com receita médica','MSRM. Efeito em 4-6 semanas.',ARRAY['náuseas','disfunção sexual','prolongamento QT'],ARRAY['não parar abrupto'],ARRAY['QT longo','IMAO'],NULL,'manual',1.0),
('Sertralina','Sertralina',NULL,ARRAY['comprimido'],ARRAY['50mg','100mg'],'ISRS antidepressivo','antidepressivo',ARRAY['depressão','ansiedade','pânico','POC'],ARRAY['depressão'],'50-200mg/dia.','com receita médica','MSRM.',ARRAY['náuseas','disfunção sexual','insónia'],ARRAY['não parar abrupto'],ARRAY['IMAO'],NULL,'manual',1.0),
('Paroxetina','Paroxetina',NULL,ARRAY['comprimido'],ARRAY['20mg'],'ISRS antidepressivo','antidepressivo',ARRAY['depressão','ansiedade','pânico'],ARRAY['depressão'],'20-40mg/dia.','com receita médica','MSRM.',ARRAY['disfunção sexual','sd. abstinência marcada'],ARRAY['retirada muito gradual'],ARRAY['IMAO','gravidez'],NULL,'manual',1.0),
('Mirtazapina','Mirtazapina',NULL,ARRAY['comprimido'],ARRAY['15mg','30mg','45mg'],'antidepressivo','antidepressivo que ajuda no sono e apetite',ARRAY['depressão','insónia associada','depressão no idoso'],ARRAY['depressão','insónia'],'15-45mg ao deitar.','com receita médica','MSRM.',ARRAY['sonolência','aumento peso','aumento apetite'],ARRAY['útil se insónia/perda de peso'],ARRAY['IMAO'],NULL,'manual',1.0),
('Duloxetina','Duloxetina',NULL,ARRAY['cápsula'],ARRAY['30mg','60mg'],'IRSN antidepressivo','antidepressivo e para dor neuropática',ARRAY['depressão','ansiedade','dor neuropática','fibromialgia'],ARRAY['depressão','dor neuropática'],'30-60mg/dia.','com receita médica','MSRM.',ARRAY['náuseas','boca seca'],ARRAY['retirada gradual'],ARRAY['IMAO','hepatopatia grave'],NULL,'manual',1.0),
('Alprazolam','Alprazolam',NULL,ARRAY['comprimido'],ARRAY['0.25mg','0.5mg','1mg'],'benzodiazepina','ansiolítico de ação rápida',ARRAY['ansiedade','pânico'],ARRAY['ansiedade'],'0.25-0.5mg até 3x/dia, curta duração.','com receita médica especial','MSRM-especial. Dependência rápida.',ARRAY['sonolência','dependência','amnésia'],ARRAY['não conduzir','não álcool','retirada gradual'],ARRAY['miastenia','apneia sono'],NULL,'manual',1.0),
('Mexazolam','Mexazolam',NULL,ARRAY['comprimido'],ARRAY['1mg'],'benzodiazepina','ansiolítico',ARRAY['ansiedade'],ARRAY['ansiedade'],'1mg 2-3x/dia.','com receita médica especial','MSRM-especial.',ARRAY['sonolência','dependência'],ARRAY['não conduzir'],ARRAY['miastenia'],NULL,'manual',1.0),
('Zolpidem','Zolpidem',NULL,ARRAY['comprimido'],ARRAY['10mg'],'hipnótico','indutor do sono',ARRAY['insónia'],ARRAY['insónia'],'10mg ao deitar, curta duração.','com receita médica especial','MSRM-especial.',ARRAY['sonolência','amnésia','comportamentos no sono'],ARRAY['tomar já deitado','não conduzir'],ARRAY['apneia do sono grave'],NULL,'manual',1.0),
('Quetiapina','Quetiapina',NULL,ARRAY['comprimido'],ARRAY['25mg','100mg','200mg','300mg'],'antipsicótico atípico','para psicose, bipolar e (off-label) insónia',ARRAY['esquizofrenia','bipolar','depressão adjuvante'],ARRAY['psicose'],'50-800mg/dia conforme indicação.','com receita médica','MSRM.',ARRAY['sedação','aumento peso','hipotensão postural'],ARRAY['vigilância metabólica'],ARRAY['demência (risco AVC)'],NULL,'manual',1.0),
('Levetiracetam','Levetiracetam',NULL,ARRAY['comprimido','solução'],ARRAY['250mg','500mg','1000mg'],'anticonvulsivante','para epilepsia',ARRAY['epilepsia'],ARRAY['convulsões'],'500-1500mg 2x/dia.','com receita médica','MSRM.',ARRAY['sonolência','irritabilidade'],ARRAY['ajuste IR'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Pregabalina','Pregabalina',NULL,ARRAY['cápsula'],ARRAY['25mg','75mg','150mg','300mg'],'gabapentinoide','para dor neuropática e ansiedade',ARRAY['dor neuropática','epilepsia','ansiedade generalizada'],ARRAY['dor neuropática','ansiedade'],'75-300mg 2x/dia.','com receita médica','MSRM. Potencial de abuso.',ARRAY['tonturas','sonolência','aumento peso'],ARRAY['retirada gradual'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Madopar','Levodopa + Benserazida',NULL,ARRAY['comprimido'],ARRAY['100+25mg','200+50mg'],'antiparkinsónico','tratamento da doença de Parkinson',ARRAY['doença de Parkinson'],ARRAY['Parkinson'],'Dose titulada, várias tomas/dia.','com receita médica','MSRM.',ARRAY['discinésias','náuseas','hipotensão postural'],ARRAY['afastar de refeições proteicas'],ARRAY['glaucoma fechado','melanoma'],NULL,'manual',1.0),
('Betahistina','Betahistina',NULL,ARRAY['comprimido'],ARRAY['8mg','16mg','24mg'],'anti-vertiginoso','para vertigens e doença de Ménière',ARRAY['vertigem','doença de Ménière'],ARRAY['tonturas','vertigem'],'8-16mg 3x/dia.','com receita médica','MSRM.',ARRAY['GI','cefaleia'],ARRAY[]::text[],ARRAY['feocromocitoma','úlcera activa'],NULL,'manual',1.0),
('Sumatriptano','Sumatriptano',NULL,ARRAY['comprimido','spray nasal'],ARRAY['50mg','100mg'],'triptano','para crise de enxaqueca',ARRAY['enxaqueca','cefaleia em salvas'],ARRAY['enxaqueca'],'50-100mg ao início, repetir após 2h se necessário.','com receita médica','MSRM.',ARRAY['pressão torácica','formigueiro','sonolência'],ARRAY['máx 200mg/dia'],ARRAY['SCA','HTA não controlada','AVC prévio'],NULL,'manual',1.0),

-- ═══ ALERGIA / DERMATO / OUTROS ═══
('Bilastina','Bilastina',NULL,ARRAY['comprimido'],ARRAY['20mg'],'anti-histamínico H1 não-sedante','para alergia sem sonolência',ARRAY['rinite alérgica','urticária'],ARRAY['alergia'],'20mg/dia em jejum.','sem receita','MNSRM.',ARRAY['raros'],ARRAY['tomar afastado de comida'],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Ebastina','Ebastina',NULL,ARRAY['comprimido'],ARRAY['10mg','20mg'],'anti-histamínico H1','para alergia',ARRAY['rinite alérgica','urticária'],ARRAY['alergia'],'10-20mg/dia.','sem receita','MNSRM.',ARRAY['cefaleia','sonolência ligeira'],ARRAY[]::text[],ARRAY['QT longo'],NULL,'manual',1.0),
('Rupatadina','Rupatadina',NULL,ARRAY['comprimido'],ARRAY['10mg'],'anti-histamínico H1','para alergia e urticária',ARRAY['rinite alérgica','urticária crónica'],ARRAY['alergia'],'10mg/dia.','sem receita','MNSRM.',ARRAY['sonolência ligeira','cefaleia'],ARRAY[]::text[],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Prednisolona','Prednisolona',NULL,ARRAY['comprimido'],ARRAY['5mg','20mg'],'corticoide oral','corticoide para inflamação/alergia',ARRAY['asma grave','alergias','doenças auto-imunes','inflamação'],ARRAY['inflamação'],'Dose individual; retirada gradual se prolongado.','com receita médica','MSRM.',ARRAY['aumento apetite','hiperglicémia','insónia','osteoporose (uso longo)'],ARRAY['não parar abrupto se uso prolongado','tomar de manhã'],ARRAY['infecção sistémica não tratada'],NULL,'manual',1.0),
('Deflazacort','Deflazacort',NULL,ARRAY['comprimido'],ARRAY['6mg','30mg'],'corticoide oral','corticoide com menos efeito no osso',ARRAY['doenças inflamatórias/auto-imunes'],ARRAY['inflamação'],'Dose individual.','com receita médica','MSRM.',ARRAY['hiperglicémia','insónia'],ARRAY['retirada gradual'],ARRAY['infecção sistémica'],NULL,'manual',1.0),
('Hidrocortisona','Hidrocortisona',NULL,ARRAY['creme','comprimido','injectável'],ARRAY['1%','10mg','100mg'],'corticoide','corticoide tópico/sistémico',ARRAY['dermatite','reacção alérgica','insuficiência suprarrenal'],ARRAY['eczema','alergia'],'Tópico 1-2x/dia; sistémico conforme indicação.','depende da dose','Creme baixa potência — MNSRM; resto receita.',ARRAY['atrofia cutânea (tópico prolongado)'],ARRAY['curta duração na face'],ARRAY['infecção cutânea não tratada'],NULL,'manual',1.0),
('Tantum Verde','Benzidamina',NULL,ARRAY['colutório','spray','pastilhas'],ARRAY['0.15%','3mg'],'anti-inflamatório local','para dor de garganta e boca',ARRAY['dor de garganta','aftas','inflamação orofaríngea'],ARRAY['dor de garganta'],'Bochechar/spray 2-3x/dia.','sem receita','MNSRM.',ARRAY['ardor local'],ARRAY[]::text[],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Stilnoct','Zolpidem',NULL,ARRAY['comprimido'],ARRAY['10mg'],'hipnótico','indutor do sono (marca)',ARRAY['insónia'],ARRAY['insónia'],'10mg ao deitar.','com receita médica especial','MSRM-especial.',ARRAY['sonolência','amnésia'],ARRAY['já deitado'],ARRAY['apneia grave'],NULL,'manual',1.0),
('Victan','Loflazepato de etilo',NULL,ARRAY['comprimido'],ARRAY['2mg'],'benzodiazepina','ansiolítico de longa duração',ARRAY['ansiedade'],ARRAY['ansiedade'],'2mg/dia.','com receita médica especial','MSRM-especial.',ARRAY['sonolência','dependência'],ARRAY['não conduzir'],ARRAY['miastenia'],NULL,'manual',1.0),

-- ═══ UROLOGIA / GINECOLOGIA / HORMONAL ═══
('Finasterida','Finasterida',NULL,ARRAY['comprimido'],ARRAY['1mg','5mg'],'inibidor 5-alfa-redutase','para HBP (5mg) e alopecia (1mg)',ARRAY['hiperplasia benigna da próstata','alopecia androgenética'],ARRAY['dificuldade urinar','queda de cabelo'],'5mg/dia (HBP) ou 1mg/dia (cabelo).','com receita médica','MSRM. Demora meses a fazer efeito.',ARRAY['disfunção sexual','ginecomastia'],ARRAY['não doar sangue','teratogénico — mulher grávida não manusear'],ARRAY['mulher fértil/grávida'],NULL,'manual',1.0),
('Tansulosina + Dutasterida','Tansulosina + Dutasterida',NULL,ARRAY['cápsula'],ARRAY['0.4+0.5mg'],'alfa-bloqueante + inibidor 5-AR','combinação para HBP',ARRAY['HBP moderada a grave'],ARRAY['sintomas urinários'],'1 cápsula/dia após a mesma refeição.','com receita médica','MSRM.',ARRAY['tonturas','disfunção sexual','ejaculação retrógrada'],ARRAY['hipotensão postural'],ARRAY['mulheres'],NULL,'manual',1.0),
('Oxibutinina','Oxibutinina',NULL,ARRAY['comprimido'],ARRAY['5mg'],'antimuscarínico','para bexiga hiperativa',ARRAY['incontinência de urgência','bexiga hiperativa'],ARRAY['urgência urinária'],'5mg 2-3x/dia.','com receita médica','MSRM.',ARRAY['boca seca','obstipação','confusão (idosos)'],ARRAY['cuidado em idosos (anticolinérgico)'],ARRAY['glaucoma fechado','retenção urinária'],NULL,'manual',1.0),
('Cerazette','Desogestrel',NULL,ARRAY['comprimido'],ARRAY['75mcg'],'contraceptivo só progestativo','pílula sem estrogénio',ARRAY['contracepção','contracepção na amamentação'],ARRAY['contracepção'],'1 comprimido/dia sem pausa, sempre à mesma hora.','com receita médica','MSRM.',ARRAY['spotting','amenorreia','acne'],ARRAY['tomar à mesma hora (janela curta)'],ARRAY['TEV activo','cancro mama'],NULL,'manual',1.0),
('Mercilon','Desogestrel + Etinilestradiol',NULL,ARRAY['comprimido'],ARRAY['0.15+0.02mg'],'contraceptivo oral combinado','pílula combinada de baixa dose',ARRAY['contracepção'],ARRAY['contracepção'],'1 comprimido/dia 21 dias + 7 pausa.','com receita médica','MSRM.',ARRAY['náuseas','TEV','spotting'],ARRAY['avaliar risco trombótico'],ARRAY['TEV','enxaqueca c/ aura','fumadora >35a'],NULL,'manual',1.0),
('Estradiol','Estradiol',NULL,ARRAY['comprimido','adesivo','gel'],ARRAY['1mg','2mg'],'hormona estrogénio','terapêutica hormonal da menopausa',ARRAY['sintomas da menopausa','osteoporose pós-menopausa'],ARRAY['afrontamentos'],'Dose individual, com progestativo se útero intacto.','com receita médica','MSRM.',ARRAY['tensão mamária','náuseas','risco TEV'],ARRAY['menor dose eficaz'],ARRAY['cancro mama','TEV','hemorragia não esclarecida'],NULL,'manual',1.0),
('Utrogestan','Progesterona',NULL,ARRAY['cápsula'],ARRAY['100mg','200mg'],'hormona progesterona','progesterona natural',ARRAY['terapêutica hormonal','suporte da gravidez','alterações menstruais'],ARRAY['hormonal'],'Conforme indicação, oral ou vaginal.','com receita médica','MSRM.',ARRAY['sonolência','tonturas'],ARRAY['tomar ao deitar'],ARRAY['hemorragia não esclarecida'],NULL,'manual',1.0),

-- ═══ OFTALMO / ORL ═══
('Maxitrol','Dexametasona + Neomicina + Polimixina',NULL,ARRAY['colírio','pomada'],NULL,'antibiótico + corticoide oftálmico','gotas para infecção/inflamação ocular',ARRAY['conjuntivite bacteriana com inflamação'],ARRAY['olho vermelho'],'1 gota 4-6x/dia.','com receita médica','MSRM.',ARRAY['ardor','aumento PIO'],ARRAY['não usar prolongado sem oftalmologia'],ARRAY['queratite herpética','infecção fúngica/viral'],NULL,'manual',1.0),
('Systane','Lágrimas artificiais',NULL,ARRAY['colírio'],NULL,'lubrificante ocular','gotas para olho seco',ARRAY['olho seco','irritação ocular'],ARRAY['olho seco'],'1 gota quando necessário.','sem receita','MNSRM.',ARRAY['visão turva momentânea'],ARRAY[]::text[],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Otosporin','Hidrocortisona + Neomicina + Polimixina',NULL,ARRAY['gotas auriculares'],NULL,'antibiótico + corticoide ótico','gotas para otite externa',ARRAY['otite externa'],ARRAY['dor de ouvido'],'3 gotas 3-4x/dia.','com receita médica','MSRM.',ARRAY['irritação local'],ARRAY['não usar se tímpano perfurado'],ARRAY['perfuração timpânica'],NULL,'manual',1.0),

-- ═══ SUPLEMENTOS / OTC ═══
('Magnesio','Magnésio',NULL,ARRAY['comprimido','saqueta'],NULL,'suplemento mineral','suplemento de magnésio',ARRAY['cãibras','défice de magnésio','fadiga'],ARRAY['cãibras'],'Conforme bula.','sem receita','MNSRM.',ARRAY['diarreia (dose alta)'],ARRAY[]::text[],ARRAY['IR grave'],NULL,'manual',1.0),
('Centrum','Multivitamínico',NULL,ARRAY['comprimido'],NULL,'suplemento multivitamínico','complexo de vitaminas e minerais',ARRAY['suplementação geral','carências'],ARRAY['cansaço'],'1 comprimido/dia.','sem receita','MNSRM.',ARRAY['raros'],ARRAY[]::text[],ARRAY['hipervitaminose'],NULL,'manual',1.0),
('Omega 3','Ácidos gordos ómega-3',NULL,ARRAY['cápsula'],NULL,'suplemento','suplemento de ómega-3',ARRAY['suporte cardiovascular','triglicéridos altos'],ARRAY['colesterol'],'1-2 cápsulas/dia.','sem receita','MNSRM.',ARRAY['eructação','GI ligeiro'],ARRAY[]::text[],ARRAY['alergia a peixe'],NULL,'manual',1.0),
('Bisolvon Tosse Seca','Dextrometorfano',NULL,ARRAY['xarope'],NULL,'antitússico','para tosse seca',ARRAY['tosse seca'],ARRAY['tosse seca'],'Conforme bula, 4-6/6h.','sem receita','MNSRM.',ARRAY['sonolência'],ARRAY['não em tosse produtiva'],ARRAY['<2 anos'],NULL,'manual',1.0),
('Carbocisteína','Carbocisteína',NULL,ARRAY['xarope','cápsula'],ARRAY['250mg/5mL','375mg'],'mucolítico','fluidifica secreções',ARRAY['tosse com expectoração'],ARRAY['tosse produtiva'],'750mg 3x/dia.','sem receita','MNSRM.',ARRAY['GI'],ARRAY[]::text[],ARRAY['úlcera activa'],NULL,'manual',1.0),

-- ═══ PEDIATRIA / OUTROS ═══
('Brufen suspensão','Ibuprofeno pediátrico',NULL,ARRAY['suspensão'],ARRAY['100mg/5mL','200mg/5mL'],'AINE pediátrico','ibuprofeno para crianças',ARRAY['febre','dor em crianças >6 meses'],ARRAY['febre criança'],'10mg/kg de 6-8/8h, com alimentos.','sem receita','MNSRM.',ARRAY['GI'],ARRAY['idade ≥6 meses','hidratação'],ARRAY['<6 meses','desidratação'],NULL,'manual',1.0),
('Clavamox','Amoxicilina + Ácido clavulânico',NULL,ARRAY['comprimido','suspensão'],ARRAY['875+125mg'],'antibiótico beta-lactâmico','antibiótico de largo espectro (marca/genérico)',ARRAY['sinusite','otite','pneumonia','ITU'],ARRAY['infecção'],'1 comprimido 12/12h.','com receita médica','MSRM.',ARRAY['diarreia','náuseas'],ARRAY['com refeições'],ARRAY['alergia penicilinas'],NULL,'manual',1.0),
('Daktacort','Miconazol + Hidrocortisona',NULL,ARRAY['creme'],ARRAY['2%+1%'],'antifúngico + corticoide tópico','creme para micose com inflamação',ARRAY['dermatofitia inflamada','intertrigo'],ARRAY['fungo','prurido'],'2x/dia, máximo 7 dias.','com receita médica','MSRM.',ARRAY['irritação local'],ARRAY['curta duração'],ARRAY['infecção viral cutânea'],NULL,'manual',1.0),
('Locoid','Hidrocortisona butirato',NULL,ARRAY['creme','pomada'],ARRAY['0.1%'],'corticoide tópico médio','creme para dermatite/eczema',ARRAY['eczema','dermatite'],ARRAY['eczema'],'1-2x/dia.','com receita médica','MSRM.',ARRAY['atrofia cutânea (uso longo)'],ARRAY['não prolongar na face'],ARRAY['rosácea','infecção cutânea'],NULL,'manual',1.0),
('Voltaren Emulgel','Diclofenac tópico',NULL,ARRAY['gel'],ARRAY['1%','2%'],'AINE tópico','gel anti-inflamatório local',ARRAY['dor muscular','contusões','dor articular'],ARRAY['dor local'],'Aplicar 3-4x/dia.','sem receita','MNSRM.',ARRAY['irritação local'],ARRAY['não em pele lesada'],ARRAY['último trimestre gravidez'],NULL,'manual',1.0),
('Canesten creme','Clotrimazol',NULL,ARRAY['creme'],ARRAY['1%'],'antifúngico tópico','creme antifúngico',ARRAY['pé de atleta','candidíase cutânea','tinea'],ARRAY['fungo'],'2x/dia 2-4 semanas.','sem receita','MNSRM.',ARRAY['irritação local'],ARRAY[]::text[],ARRAY['hipersensibilidade'],NULL,'manual',1.0),

-- ═══ TÓNICOS / VENDA LIVRE (corrigir prescrição — são SEM receita) ═══
('Guronsan','Cafeína + Ácido ascórbico + Aspartato de arginina',NULL,ARRAY['comprimido efervescente'],NULL,'tónico estimulante','um tónico de venda livre que ajuda a combater a fadiga passageira (cafeína + vitamina C + aspartato de arginina)',ARRAY['fadiga passageira','cansaço','astenia'],ARRAY['cansaço','fadiga'],'1-2 comprimidos por dia dissolvidos em água, de manhã/almoço. Não tomar à noite (cafeína).','sem receita','MNSRM (venda livre). NÃO precisa de receita.',ARRAY['nervosismo','insónia','palpitações (pela cafeína)'],ARRAY['evitar à noite','moderar se sensível à cafeína'],ARRAY['hipertensão grave','arritmias','ansiedade marcada'],'Não substitui descanso nem trata causas de cansaço persistente.','manual',1.0),
('Cerebrum','Ácido glutâmico + fósforo + vitaminas',NULL,ARRAY['ampola bebível'],NULL,'tónico','tónico de venda livre para fadiga física e mental',ARRAY['fadiga','astenia','dificuldade de concentração'],ARRAY['cansaço'],'1 ampola por dia.','sem receita','MNSRM (venda livre).',ARRAY['raros'],ARRAY[]::text[],ARRAY['hipersensibilidade'],NULL,'manual',1.0),
('Absorvit','Multivitamínico + minerais',NULL,ARRAY['comprimido','ampola'],NULL,'suplemento','suplemento vitamínico de venda livre',ARRAY['fadiga','convalescença','suporte vitamínico'],ARRAY['cansaço'],'Conforme bula.','sem receita','MNSRM.',ARRAY['raros'],ARRAY[]::text[],ARRAY['hipervitaminose'],NULL,'manual',1.0),
('Aspegic','Ácido acetilsalicílico',NULL,ARRAY['saqueta'],ARRAY['100mg','500mg','1000mg'],'analgésico antipirético','AAS em pó solúvel para dor e febre',ARRAY['dor ligeira a moderada','febre'],ARRAY['dor','febre'],'500-1000mg até 3x/dia, dissolvido em água.','sem receita','MNSRM nas doses analgésicas.',ARRAY['azia','hemorragia digestiva'],ARRAY['com alimentos','não em crianças com viroses'],ARRAY['úlcera activa','crianças (sd. Reye)'],NULL,'manual',1.0),
('Cêgripe','Paracetamol + Cafeína + Clorfeniramina + Fenilefrina',NULL,ARRAY['comprimido'],NULL,'antigripal de venda livre','medicamento de venda livre para sintomas de gripe e constipação',ARRAY['gripe','constipação','congestão nasal','dores'],ARRAY['gripe','constipação'],'1-2 comprimidos até 3x/dia.','sem receita','MNSRM.',ARRAY['sonolência','boca seca','insónia (cafeína)'],ARRAY['cuidado com HTA','não conduzir'],ARRAY['HTA grave','glaucoma fechado'],NULL,'manual',1.0)

on conflict (lower(coalesce(brand_name,'')), lower(active_ingredient)) do nothing;
